name: Auto PR and Merge
on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        id: pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated updates"
          title: "Automated updates $(date +'%Y-%m-%d')"
          body: "This is an automated PR"
          branch: "auto-update-$(date +%Y%m%d)"
          base: "main"
          labels: "automated"

  auto-merge:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.15.6
        if: ${{ needs.create-pr.outputs.pr-created == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automated"
          MERGE_METHOD: "squash"