name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Nécessaire pour interagir avec les PRs

    steps:
      - name: Auto Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          intervalSeconds: 10
          timeoutSeconds: 30
